In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Mounting Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
# Importing the dataset
dataset = pd.read_csv('/content/drive/My Drive/ML lab/practice-test/CLASSIFICATION DATASET.csv')

In [4]:
print(dataset)

     age   cp  trestbps   chol  fbs  ... oldpeak slope   ca  thal  heartdisease
0     63  1.0     145.0  233.0  1.0  ...     2.3   3.0  0.0     6             0
1     67  4.0     160.0  286.0  0.0  ...     1.5   2.0  3.0     3             2
2     67  NaN     120.0  229.0  0.0  ...     2.6   2.0  2.0     7             1
3     37  3.0     130.0  250.0  0.0  ...     3.5   3.0  0.0     3             0
4     41  2.0     130.0  204.0  0.0  ...     1.4   1.0  0.0     3             0
..   ...  ...       ...    ...  ...  ...     ...   ...  ...   ...           ...
298   45  1.0     110.0  264.0  0.0  ...     2.0   0.0  7.0     1             0
299   68  4.0     144.0  193.0  1.0  ...     2.0   2.0  7.0     2             0
300   57  4.0     130.0  131.0  0.0  ...     2.0   1.0  7.0     3             0
301   57  2.0     130.0  236.0  0.0  ...     2.0   1.0  3.0     1             0
302   38  3.0     138.0  175.0  0.0  ...     1.0   NaN  3.0     0             0

[303 rows x 15 columns]


In [5]:
print(dataset.shape)
dataset.info()

(303, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   age           303 non-null    int64  
 1   cp            281 non-null    float64
 2   trestbps      292 non-null    float64
 3   chol          289 non-null    float64
 4   fbs           285 non-null    float64
 5   Gender        289 non-null    object 
 6   Geography     290 non-null    object 
 7   restecg       297 non-null    float64
 8   thalach       294 non-null    float64
 9   exang         294 non-null    float64
 10  oldpeak       291 non-null    float64
 11  slope         289 non-null    float64
 12  ca            284 non-null    float64
 13  thal          303 non-null    int64  
 14  heartdisease  303 non-null    int64  
dtypes: float64(10), int64(3), object(2)
memory usage: 35.6+ KB


In [6]:
types = dataset.dtypes
print(types)

age               int64
cp              float64
trestbps        float64
chol            float64
fbs             float64
Gender           object
Geography        object
restecg         float64
thalach         float64
exang           float64
oldpeak         float64
slope           float64
ca              float64
thal              int64
heartdisease      int64
dtype: object


In [8]:
class_counts = dataset.groupby('Geography').size()
print(class_counts)

Geography
France    201
Spain      89
dtype: int64


In [17]:
# Extracting dependent and independent variables:
# Extracting independent variable:
X = dataset.iloc[:,0:14].values
# Extracting dependent variable:
y = dataset.iloc[:, 14].values

In [18]:
print(X)

[[63 1.0 145.0 ... 3.0 0.0 6]
 [67 4.0 160.0 ... 2.0 3.0 3]
 [67 nan 120.0 ... 2.0 2.0 7]
 ...
 [57 4.0 130.0 ... 1.0 7.0 3]
 [57 2.0 130.0 ... 1.0 3.0 1]
 [38 3.0 138.0 ... nan 3.0 0]]


In [19]:
print(y)

[0 2 1 0 0 0 3 0 2 1 0 0 2 0 0 0 1 0 0 0 0 0 1 3 4 0 0 0 0 0 2 1 0 0 0 3 0
 2 1 0 0 2 0 0 0 1 0 0 0 0 0 1 3 4 0 0 0 0 0 2 1 0 0 0 3 0 2 1 0 0 2 0 0 0
 1 0 0 0 0 0 1 3 4 0 0 0 0 0 2 1 0 0 0 3 0 2 1 0 0 2 0 0 0 1 0 0 0 0 0 1 3
 4 0 0 0 0 0 2 1 0 0 0 3 0 2 1 0 0 2 0 0 0 1 0 0 0 0 0 1 3 4 0 0 0 0 0 2 1
 0 0 0 3 0 2 1 0 0 2 0 0 0 1 0 0 0 0 0 1 3 4 0 0 0 0 0 2 1 0 0 0 3 0 2 1 0
 0 2 0 0 0 1 0 0 0 0 0 1 3 4 0 0 0 0 0 2 1 0 0 0 3 0 2 1 0 0 2 0 0 0 1 0 0
 0 0 0 1 3 4 0 0 0 0 0 2 1 0 0 0 3 0 2 1 0 0 2 0 0 0 1 0 0 0 0 0 1 3 4 0 0
 0 0 0 2 1 0 0 0 3 0 2 1 0 0 2 0 0 0 1 0 0 0 0 0 1 3 4 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0]


In [20]:
dataset.isnull().sum()

age              0
cp              22
trestbps        11
chol            14
fbs             18
Gender          14
Geography       13
restecg          6
thalach          9
exang            9
oldpeak         12
slope           14
ca              19
thal             0
heartdisease     0
dtype: int64

In [29]:
# Taking care of missing data
#handling missing data (Replacing missing data with the mean value)  
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values= np.NAN, strategy= 'mean', fill_value=None, verbose=1, copy=True)
#Fitting imputer object to the independent variables x.   
imputer = imputer.fit(X[:, 1:5]) 
#Replacing missing data with the calculated mean value  
X[:, 1:5]= imputer.transform(X[:, 1:5])  

In [26]:
# Taking care of missing data
#handling missing data (Replacing missing data with the mean value)  
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values= np.NAN, strategy= 'mean', fill_value=None, verbose=1, copy=True)
#Fitting imputer object to the independent variables x.   
imputer = imputer.fit(X[:, 7:13]) 
#Replacing missing data with the calculated mean value  
X[:, 7:13]= imputer.transform(X[:, 7:13])

In [36]:
# Taking care of missing data
#handling missing data (Replacing missing data with the mean value)  
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values= np.NAN, strategy= 'constant', fill_value="female", verbose=1, copy=True)
#Fitting imputer object to the independent variables x.   
imputer = imputer.fit(X[:, 5:6]) 
#Replacing missing data with the calculated mean value  
X[:, 5:6]= imputer.transform(X[:, 5:6])

In [189]:
# Taking care of missing data
#handling missing data (Replacing missing data with the mean value)  
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values= np.NAN, strategy= 'constant', fill_value="Spain", verbose=1, copy=True)
#Fitting imputer object to the independent variables x.   
imputer = imputer.fit(X[:, 6:7]) 
#Replacing missing data with the calculated mean value  
X[:, 6:7]= imputer.transform(X[:, 6:7])

In [190]:
# Encoding Categorical data:
# Encoding the Independent Variable
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X[:, 5] = labelencoder_X.fit_transform(X[:, 5])

In [191]:
# Encoding Categorical data:
# Encoding the Independent Variable
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X[:, 6] = labelencoder_X.fit_transform(X[:, 6])

In [192]:
print(X)

[[63 1.0 145.0 ... 3.0 0.0 6.0]
 [67 4.0 160.0 ... 2.0 3.0 3.0]
 [67 3.1637010676156585 120.0 ... 2.0 2.0 7.0]
 ...
 [57 4.0 130.0 ... 1.0 7.0 3.0]
 [57 2.0 130.0 ... 1.0 3.0 1.0]
 [38 3.0 138.0 ... 0.7993079584775087 3.0 0.0]]


In [193]:
dataframe=pd.DataFrame(X,columns=['age','cp','trestbps','chol', 'fbs', 'Gender ', 'Geography', 
                                  'restecg' ,'thalach','exang', 'oldpeak','slope', 'ca', 'thal'])
dataframe.isnull().sum()

age          0
cp           0
trestbps     0
chol         0
fbs          0
Gender       0
Geography    0
restecg      0
thalach      0
exang        0
oldpeak      0
slope        0
ca           0
thal         0
dtype: int64

In [194]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 5)

In [195]:
print(X_train)

[[44 4.0 120.0 ... 0.0 6.0 2.0]
 [62 3.1637010676156585 140.0 ... 3.0 2.0 3.0]
 [57 4.0 128.0 ... 1.0 3.0 0.0]
 ...
 [63 4.0 130.0 ... 3.0 7.0 3.0]
 [69 3.0 140.0 ... 3.0 7.0 2.0]
 [58 4.0 128.0 ... 2.0 7.0 3.0]]


In [196]:
print(X_test)

[[38 3.0 138.0 ... 0.7993079584775087 3.0 0.0]
 [61 1.0 134.0 ... 2.0 3.0 2.0]
 [40 4.0 152.0 ... 0.0 7.0 1.0]
 ...
 [74 2.0 120.0 ... 1.0 3.0 0.0]
 [52 3.0 138.0 ... 0.7993079584775087 3.0 0.0]
 [58 4.0 125.0 ... 2.0 7.0 1.0]]


In [197]:
print(y_test)

[0 0 0 0 4 3 0 0 0 0 0 0 0 1 0 1 1 0 1 0 0 2 0 0 0 0 0 2 0 0 0 1 0 3 1 1 0
 0 0 1 2 2 2 4 3 0 0 0 1 0 2 0 0 0 0 0 0 0 1 0 1 0 2 2 0 0 2 1 0 0 3 0 4 2
 0 2]


In [198]:
print(y_train)

[0 3 0 0 0 2 0 0 0 0 0 2 1 0 3 0 0 1 0 0 0 0 1 0 2 1 2 0 0 0 0 0 0 0 0 0 1
 3 0 0 2 0 4 0 3 1 0 0 1 0 1 0 3 0 3 0 0 1 0 0 0 1 0 2 0 0 0 1 0 3 0 0 1 0
 0 0 0 0 0 3 2 0 0 0 0 0 0 0 0 2 0 2 0 0 0 0 0 3 0 0 0 0 0 0 2 0 0 0 0 0 4
 0 4 0 0 0 0 0 1 3 3 0 0 0 0 0 0 4 3 2 0 0 3 0 0 0 3 0 0 4 0 0 0 0 0 0 3 0
 0 0 2 4 0 2 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 1 1 0 0 0 0 1 1
 0 1 0 0 1 0 0 0 0 0 3 4 0 0 1 0 2 0 1 2 1 0 2 0 0 1 0 0 1 0 2 0 0 0 0 0 0
 2 0 1 0 0]


In [199]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [200]:
print(X_train)

[[-1.17267002  0.87457383 -0.66022167 ... -0.83422648  0.71546386
   0.32535761]
 [ 0.80730093 -0.02429793  0.4588685  ...  2.2367437  -1.04929134
   0.90235899]
 [ 0.257309    0.87457383 -0.2125856  ...  0.18943025 -0.60810254
  -0.82864516]
 ...
 [ 0.91729932  0.87457383 -0.10067658 ...  2.2367437   1.15665266
   0.90235899]
 [ 1.57728963 -0.2002473   0.4588685  ...  2.2367437   1.15665266
   0.32535761]
 [ 0.36730739  0.87457383 -0.2125856  ...  1.21308697  1.15665266
   0.90235899]]


In [201]:
print(X_test)

[[-1.83266034 -0.2002473   0.34695948 ... -0.01600951 -0.60810254
  -0.82864516]
 [ 0.69730255 -2.34988956  0.12314145 ...  1.21308697 -0.60810254
   0.32535761]
 [-1.61266356  0.87457383  1.1303226  ... -0.83422648  1.15665266
  -0.25164377]
 ...
 [ 2.12728157 -1.27506843 -0.66022167 ...  0.18943025 -0.60810254
  -0.82864516]
 [-0.29268293 -0.2002473   0.34695948 ... -0.01600951 -0.60810254
  -0.82864516]
 [ 0.36730739  0.87457383 -0.38044912 ...  1.21308697  1.15665266
  -0.25164377]]


In [210]:
# Fitting Decision Tree Classification to the Training set
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 33)
classifier.fit(X_train, y_train)


DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=33, splitter='best')

In [211]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [212]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print('Confusion matrix: ')
print(cm)

Confusion matrix: 
[[32  8  3  1  2]
 [ 8  2  1  0  1]
 [ 9  2  0  0  0]
 [ 3  1  0  0  0]
 [ 2  0  1  0  0]]


In [213]:

# calculate Accuracy
#   0   1
# 0[59  7(FP type 1)]
#1 [ 11(FN Type 2) 23]= 82/100

from sklearn.metrics import accuracy_score
print('Accuracy: %.2f' % (accuracy_score(y_test, y_pred)*100))

Accuracy: 44.74


In [214]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
# calculate precision
# Precision = TruePositives / (TruePositives + FalsePositives) 
# calculate Accuracy
#   0   1
# 0[59  7(FP type 1)]
#1 [ 11(FN Type 2) 23]= 82/100
precision = precision_score(y_test, y_pred, average='micro')
print('Precision: %.3f' % (precision))

Precision: 0.447


In [215]:
# F-Measure = (2 * Precision * Recall) / (Precision + Recall)
# (2*0.829*0.906)/0.829+0.906
# calculate score
score = f1_score(y_test, y_pred, average='micro')
print('F-Measure: %.3f' % (score*100))

F-Measure: 44.737


In [216]:
age =  35#@param {type:"number"}
cp = 3#@param {type:"number"}
trestbps = 100 #@param["1","0"] {type:"raw",allow-input: true}
chol = 300#@param {type:"number"}
fbs = 0#@param {type:"number"}
Gender = 1#@param {type:"number"}
Geography = 1#@param {type:"number"}
restecg = 100#@param {type:"number"}
thalach  = 270#@param {type:"number"}
exang = 5#@param {type:"number"}
oldpeak = 3#@param {type:"number"}
slope = 2#@param {type:"number"}
ca  = 5#@param {type:"number"}
thal = 5#@param {type:"number"}

output= classifier.predict(sc.transform([[age,cp,trestbps,chol, fbs,
                                          Gender, Geography,restecg,
                                          thalach, exang,oldpeak, slope,
                                          ca, thal]]))
print("Heart Disease", output)
if output==[0]:
  print("It is HeartDisease Catogory 0")
elif output==[1]:
  print("It is HeartDisease Catogory 1")
elif output==[2]:
  print("It is HeartDisease Catogory 2")
elif output==[3]:
  print("It is HeartDisease Catogory 3")
elif output==[4]:
  print("It is HeartDisease Catogory 4")

Heart Disease [3]
It is HeartDisease Catogory 3


In [217]:
import pickle 
print("[INFO] Saving model...")
# Save the trained model as a pickle string. 
saved_model=pickle.dump(classifier,open('/content/drive/My Drive/ML lab/practice-test/decision_model.pkl', 'wb')) 
# Saving model to disk

[INFO] Saving model...


In [218]:
# Load the pickled model 
model = pickle.load(open('/content/drive/My Drive/ML lab/practice-test/decision_model.pkl','rb'))  
# Use the loaded pickled model to make predictions 
model.predict(X_test) 

array([1, 0, 0, 0, 2, 0, 0, 4, 2, 0, 0, 0, 0, 2, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 2, 1, 1, 0, 0, 0, 1, 0, 4, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 2, 1, 0, 0, 0, 4, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 3, 0, 0, 0, 0, 0, 0, 0])

In [219]:
# save the model to disk
import joblib
filename = '/content/drive/My Drive/ML lab/practice-test/finalized_model.sav'
joblib.dump(classifier, filename)

['/content/drive/My Drive/ML lab/practice-test/finalized_model.sav']

In [220]:
!pip install streamlit

In [221]:
# Load the pickled model
import pickle
pickle_in = open("/content/drive/My Drive/ML lab/practice-test/decision_model.pkl","rb")
model=pickle.load(pickle_in)

In [238]:
%%writefile app.py
import streamlit as st 
from PIL import Image
import pickle
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
st.set_option('deprecation.showfileUploaderEncoding', False)
# Load the pickled model
pickle_in = open("/content/drive/My Drive/ML lab/practice-test/decision_model.pkl","rb")
model=pickle.load(pickle_in)
dataset= pd.read_csv('/content/drive/My Drive/ML lab/practice-test/CLASSIFICATION DATASET.csv')
# Extracting independent variable:
X = dataset.iloc[:,0:14].values
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values= np.NAN, strategy= 'mean', fill_value=None, verbose=1, copy=True) 
imputer = imputer.fit(X[:, 1:5])  
X[:, 1:5]= imputer.transform(X[:, 1:5])  
imputer = imputer.fit(X[:, 7:13])  
X[:, 7:13]= imputer.transform(X[:, 7:13])

imputer = SimpleImputer(missing_values= np.NAN, strategy= 'constant', fill_value="female", verbose=1, copy=True)
imputer = imputer.fit(X[:, 5:6])   
X[:, 5:6]= imputer.transform(X[:, 5:6])
imputer = SimpleImputer(missing_values= np.NAN, strategy= 'constant', fill_value="", verbose=1, copy=True)
imputer = imputer.fit(X[:, 6:7])   
X[:, 6:7]= imputer.transform(X[:, 6:7])

from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X[:, 5] = labelencoder_X.fit_transform(X[:, 5])
labelencoder_X = LabelEncoder()
X[:, 6] = labelencoder_X.fit_transform(X[:, 6])


from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)
def predict_note_authentication(age,cp,trestbps,chol, fbs,
                                Gender, Geography,restecg,
                                thalach, exang,oldpeak, slope,
                                ca, thal):
  output= model.predict(sc.transform([[age,cp,trestbps,chol, fbs,
                                      Gender, Geography,restecg,
                                      thalach, exang,oldpeak, slope,
                                      ca, thal]]))
  print("Heart Disease", output)
  if output==[0]:
    prediction ="It is HeartDisease Catogory 0"
  elif output==[1]:
    prediction ="It is HeartDisease Catogory 1"
  elif output==[2]:
    prediction ="It is HeartDisease Catogory 2"
  elif output==[3]:
    prediction ="It is HeartDisease Catogory 3"
  elif output==[4]:
    prediction ="It is HeartDisease Catogory 4"
  print(prediction)
  return prediction
def main():
    st.title("HeartDisease Prediction")
    html_temp = """
   <div class="" style="background-color:blue;" >
   <div class="clearfix">           
   <div class="col-md-12">
   <center><p style="font-size:40px;color:white;margin-top:10px;">Poornima Institute of Engineering & Technology</p></center> 
   <center><p style="font-size:30px;color:white;margin-top:10px;">Department of Computer Engineering</p></center> 
   <center><p style="font-size:25px;color:white;margin-top:10px;">Ml Lab Experiment Deployment</p></center> 
   </div>
   </div>
   </div>
   """
    st.markdown(html_temp,unsafe_allow_html=True)
    
    age = st.text_input("age","Type Here")
    cp = st.text_input("cp","Type Here")
    trestbps = st.text_input("trestbps","Type Here")
    chol = st.text_input("chol","Type Here")
    fbs = st.text_input("fbs","Type Here")
    Gender = st.text_input("Gender","Type Here")
    Geography = st.text_input("Geography","Type Here")
    restecg = st.text_input("restecg","Type Here")
    thalach = st.text_input("thalach","Type Here")
    exang = st.text_input("exang","Type Here")
    oldpeak = st.text_input("oldpeak","Type Here")
    slope = st.text_input("slope","Type Here")
    ca = st.text_input("ca","Type Here")
    thal = st.text_input("thal","Type Here")

    resul=""
    if st.button("Predict"):
      result=predict_note_authentication(age,cp,trestbps,chol, fbs,
                                          Gender, Geography,restecg,
                                          thalach, exang,oldpeak, slope,
                                          ca, thal)
      st.success('Model has predicted {}'.format(result))
    if st.button("About"):
      st.text("Developed by Pritesh Kumar")

if __name__=='__main__':
  main()
   

Overwriting app.py


In [239]:
!nohup streamlit run  app.py &

nohup: appending output to 'nohup.out'


In [240]:
!pip install pyngrok

In [241]:
!ngrok authtoken 1l8Chfa8ulSrjVty4nEKYRIGimv_434sL7Gi9k1AszUCPjjp1


Authtoken saved to configuration file: /root/.ngrok2/ngrok.yml


In [242]:
from pyngrok import ngrok
url=ngrok.connect(port='8050')
url

<NgrokTunnel: "http://b80557ea91bd.ngrok.io" -> "http://localhost:80">

In [243]:
 !streamlit run --server.port 80 app.py

2021-05-05 07:57:53.799 An update to the [server] config option section was detected. To have these changes be reflected, please restart streamlit.

  You can now view your Streamlit app in your browser.

  Network URL: http://172.28.0.2:80
  External URL: http://34.122.72.205:80

Heart Disease [3]
It is HeartDisease Catogory 3
Heart Disease [3]
It is HeartDisease Catogory 3
  Stopping...


In [244]:
ngrok.kill()